extends Node

enum SLOT_ID {EMPTY, SQUARE_LIGHT, SQUARE_DARK, PATH,
LIGHT_PIECE_PAWN, LIGHT_PIECE_ROOK, LIGHT_PIECE_KNIGHT, LIGHT_PIECE_BISHOP, LIGHT_PIECE_QUEEN, LIGHT_PIECE_KING,
DARK_PIECE_PAWN, DARK_PIECE_ROOK, DARK_PIECE_KNIGHT, DARK_PIECE_BISHOP, DARK_PIECE_QUEEN, DARK_PIECE_KING}

var NEXT_MAP = "Pawn-0"
var CHESS_SCENE

var CHESS_BOARD_SETUP

#Two slots, 1 is start, 2 is to swap with
#Column, Row, SLOT_ID
var TO_MOVE = [[0,0,0], [0,0,0]]
